### ISSUE TITLE
Cannot download the Event Addon

### ISSUE THREAD

**Issue by matt1as** [SAP-samples/cloud-extension-ecc-business-process#1]
I cannot find the Event Enablement Add-On required in the SWDC. I'm logged in with a S-user with authorization to download packages, and we have a valid ERP license. Did it change name?

**Comment by ejazsyed** [comment]
Hi,

Please find the Add-on package from the below link of software Centre.

https://launchpad.support.sap.com/#/softwarecenter/search/asanwee
