### ISSUE TITLE
App crashed when deploy to BTP using MTA

### ISSUE THREAD

**Issue by ZhongpinWang** [SAP-samples/cloud-extension-ecc-business-process#26]
Dear colleagues,

I was trying to deploy the mock server to BTP, and I got the following error logs:

| Time | Event | Actor | Description |
| -- | -- | -- | -- |
|27 Jun 2023, 18:30:21 (GMT+02:00) | app.crash | mock-srv | instance: 8f7a18b2-eaac-4ecb-5c0e-6ac5, index: 0, cell_id: c839c7b1-088e-41af-b9b7-66256aacd457, exit_description: Instance never healthy after 1m0.246s: Timed out after 1m0s (30 attempts) waiting for readiness check to succeed: failed to make TCP connection to 10.157.242.83:8080: dial tcp 10.157.242.83:8080: connect: connection refused; process did not exit, reason: CRASHED | 
| 27 Jun 2023, 18:30:21 (GMT+02:00) | audit.app.process.crash | web | instance: 8f7a18b2-eaac-4ecb-5c0e-6ac5, index: 0, cell_id: c839c7b1-088e-41af-b9b7-66256aacd457, reason: CRASHED, exit_description: Instance never healthy after 1m0.246s: Timed out after 1m0s (30 attempts) waiting for readiness check to succeed: failed to make TCP connection to 10.157.242.83:8080: dial tcp 10.157.242.83:8080: connect: connection refused; process did not exit, crash_count: 1, crash_timestamp: 1687883421598257000, version: d61a09ed-ce83-4647-8b87-d8242d0571b2 |

I am using a BTP trial account in Zone US10. Could you please help me with this?

Regards,
Zhongpin Wang

**Comment by navinkrishnan** [comment]
Hi @ZhongpinWang Please specify your `node` version.

**Comment by ZhongpinWang** [comment]
Hi @navinkrishnan,

Thanks for the quick reply. These are the versions on my local machine:

node: `v16.20.0`
npm: `8.19.4`
cf cli: `cf version 8.7.1+9c81242.2023-06-15`
mbt: `Cloud MTA Build Tool version 1.2.23`

The package was built by the `nodejs_buildpack`.

Regards,
Zhongpin

**Comment by ZhongpinWang** [comment]
Now, it seems to work only after I change the instance memory from 256MB to 512MB.

Since the problem is "solved", I will close this issue now. But it would be nice if the memory requirement could be documented somewhere. Also in this mission [Install Mock Server](https://discovery-center.cloud.sap/protected/index.html#/mymissiondetail/65186/card/9784177/?tab=projectboard).

Thanks a lot!
